---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: '12'
  #environments_path: test/environments

platforms:
  - name: bento/ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04
      network:
        - ["private_network", { type: "dhcp" }]

suites:
  - name: default
    run_list:
      - recipe[lamp_stack::default]
    attributes:
