name             'et_apache_test-cookbook/'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures et_apache_test-cookbook/'
long_description 'Installs/Configures et_apache_test-cookbook/'
version          '0.1.0'
depends			 'apache2', '~> 3.1'
