name             'et_apache_test-cookbook/'
maintainer       'Eddie Pratt '
maintainer_email 'pratt.e@husky.neu.edu'
license          'All rights reserved'
description      'Installs/Configures et_apache_test-cookbook/'
long_description 'Installs/Configures et_apache_test-cookbook/'
version          '0.1.0'
depends		'apache2', '~> 3.1'
depends		'java'
